server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: 'postgres'
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
