server.port=8081
spring.application.name=product

spring.datasource.url=jdbc:postgresql://localhost:5432/microservicer-product-service
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
