server.port=8082
spring.application.name=product-category

spring.datasource.url=jdbc:postgresql://localhost:5432/microservicer-product-category-service
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
